"""Extract the supplied Home SVG into reusable, text-free Roblox UI assets.

Run this, then render_home_assets.mjs. Every SVG retains its gradient,
filter, symbol and clip definitions; no text is rasterized into an asset.
"""
from __future__ import annotations

import copy
import json
from pathlib import Path
import xml.etree.ElementTree as ET

HERE = Path(__file__).resolve().parent
OUT = HERE / "home"
SOURCE = OUT / "forge-ugc.svg"
NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", NS)
ET.register_namespace("xlink", "http://www.w3.org/1999/xlink")


def generate_module() -> None:
    manifest = json.loads((OUT / "manifest.json").read_text(encoding="utf-8"))
    ids_path = OUT / "asset_ids.json"
    ids = json.loads(ids_path.read_text(encoding="utf-8")) if ids_path.exists() else {}
    lines = ["--!strict", "", "-- GENERATED by design/export_home_assets.py or design/upload_home_assets.mjs.",
             "-- IDs are raw Image assets, usable directly by ImageLabel/ImageButton.",
             "local HomeAssets = {"]
    for item in manifest:
        lines.append(f'\t{item["name"]} = {int(ids.get(item["name"], 0))},')
    lines += ["}", "", "return table.freeze(HomeAssets)", ""]
    (HERE.parent / "src" / "Shared" / "HomeAssets.luau").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    tree = ET.parse(SOURCE)
    root = tree.getroot()
    by_id = {e.get("id"): e for e in root.iter() if e.get("id")}
    defs = by_id.get("defs") or root.find(f"{{{NS}}}defs")
    assert defs is not None
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "svg").mkdir(exist_ok=True)
    specs = []

    def group(name):
        return by_id[name]

    def subset(parent, children):
        wrapper = ET.Element(parent.tag, {k: v for k, v in parent.attrib.items() if k != "id"})
        for child in children:
            wrapper.append(copy.deepcopy(child))
        return wrapper

    def asset(name, rect, elements, *, slice_center=None):
        x, y, w, h = rect
        svg = ET.Element(f"{{{NS}}}svg", {"width": str(w * 2), "height": str(h * 2),
                         "viewBox": f"{x} {y} {w} {h}"})
        svg.append(copy.deepcopy(defs))
        for element in elements:
            svg.append(copy.deepcopy(element))
        # Remove lettering even in definitions/nested groups, never just hide it.
        for parent in list(svg.iter()):
            for child in list(parent):
                if child.tag.rsplit("}", 1)[-1] in {"text", "tspan", "textPath", "title", "desc"}:
                    parent.remove(child)
        assert not any(e.tag.rsplit("}", 1)[-1] in {"text", "tspan", "textPath"} for e in svg.iter())
        serialized = ET.tostring(svg, encoding="unicode", xml_declaration=True)
        (OUT / "svg" / f"{name}.svg").write_text(
            "\n".join(line.rstrip() for line in serialized.splitlines()) + "\n", encoding="utf-8"
        )
        entry = {"name": name, "file": f"png/{name}.png", "rect": list(rect), "scale": 2}
        if slice_center:
            entry["sliceCenter"] = [v * 2 for v in slice_center]
        specs.append(entry)

    def symbol(name, symbol_id, size=48, glow=None):
        g = ET.Element(f"{{{NS}}}g", {"filter": f"url(#{glow})"} if glow else {})
        ET.SubElement(g, f"{{{NS}}}use", {"href": f"#{symbol_id}", "x": "12", "y": "12",
                                            "width": str(size), "height": str(size)})
        asset(name, (0, 0, size + 24, size + 24), [g])

    asset("Backdrop", (0, 0, 1672, 941), [group("blurred-city-backdrop")])
    asset("Dashboard", (18, 84, 1634, 838), [group("main-dashboard")], slice_center=(65, 85, 1570, 750))
    asset("LogoMark", (68, 0, 320, 228), [group("forge-ugc-logo")])
    nav = list(group("main-navigation"))
    asset("NavBar", (375, 126, 1005, 98), nav[:2], slice_center=(40, 30, 965, 68))
    asset("NavActive", (374, 125, 268, 102), nav[2:4], slice_center=(40, 35, 228, 67))
    for name, ref in [("NavHome", "home-icon"), ("NavCreate", "cube-icon"),
                      ("NavMarket", "bag-icon"), ("NavGames", "pad-icon")]:
        symbol(name, ref)

    facets = list(group("card-facets"))
    reflections = list(group("top-card-reflections"))
    border = list(group("card-border-light"))
    for i, (name, background, art_id, x, width) in enumerate([
        ("Create", "create-card-background", "left-art", 77, 505),
        ("Market", "shop-card-background", "shop-art", 606, 504),
        ("Games", "games-card-background", "game-art", 1135, 472),
    ]):
        asset(f"{name}Panel", (x - 12, 232, width + 24, 514),
              [subset(group("card-border-light"), [border[i]]), group(background),
               subset(group("card-facets"), facets[i * 2:i * 2 + 2]), reflections[i]],
              slice_center=(45, 45, width - 21, 469))
        # Keep the clip parent, so decorative art cannot spill into another card.
        clip_parent = next(e for e in root if e.get("clip-path") == f'url(#{["left", "shop", "game"][i]}-clip)')
        asset(f"{name}Art", (x, 244, width, 490), [clip_parent])

    for name, ref, x, width in [("CreateButton", "blue-button-action", 100, 459),
                                ("MarketButton", "purple-button-action", 629, 459),
                                ("GamesButton", "gold-button-action", 1158, 426)]:
        button = copy.deepcopy(group(ref))
        # Chevron is a separate asset, positioned beside the editable caption.
        button.remove(list(button)[-1])
        asset(name, (x - 10, 630, width + 20, 102), [button], slice_center=(45, 40, width - 25, 62))
    arrow = list(group("blue-button-action"))[-1]
    asset("Arrow", (422, 663, 24, 30), [arrow])

    currency = list(group("currency-and-settings"))
    asset("ResourcePill", (1135, 19, 219, 88), [currency[0]], slice_center=(42, 32, 177, 56))
    asset("TokenIcon", (1144, 26, 67, 68), [currency[1]])
    asset("TicketIcon", (1356, 28, 70, 66), [currency[6]])
    asset("PlusButton", (1280, 28, 66, 66), currency[3:5])
    asset("SettingsButton", (1563, 19, 84, 88), currency[10:])

    quick = list(group("link-tutorial"))
    asset("QuickLink", (67, 752, 312, 128), quick[:1], slice_center=(40, 35, 272, 93))
    for name, ref, glow in [("TutorialIcon", "book-icon", "cyan-glow"),
                            ("MissionsIcon", "missions-icon", "cyan-glow"),
                            ("RewardsIcon", "gift-icon", "purple-glow"),
                            ("CodesIcon", "people-icon", "cyan-glow"),
                            ("PremiumIcon", "star-icon", "gold-glow")]:
        symbol(name, ref, 75, glow)

    (OUT / "manifest.json").write_text(json.dumps(specs, indent=2) + "\n", encoding="utf-8")
    if not (OUT / "asset_ids.json").exists():
        (OUT / "asset_ids.json").write_text("{}\n", encoding="utf-8")
    generate_module()
    print(f"Extracted {len(specs)} text-free SVG components at 2x resolution.")


if __name__ == "__main__":
    import sys
    generate_module() if "--apply-ids" in sys.argv else main()
