// Upload text-free PNG components as raw Images and update HomeAssets.luau.
// Node 22+, no package installation. Credentials stay in an ignored local file.
import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { verifySvgPng } from './svg_png_guard.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const dir = path.join(here, 'home');
const api = 'https://apis.roblox.com/assets/v1';
const args = process.argv.slice(2);
const value = (flag) => args.includes(flag) ? args[args.indexOf(flag) + 1] : undefined;
const envFile = path.resolve(value('--env') || path.join(here, '../backend/.env.roblox-upload'));
const dryRun = args.includes('--dry-run');
const only = value('--only')?.split(',');
const manifest = JSON.parse(await fs.readFile(path.join(dir, 'manifest.json'), 'utf8'));
const selected = manifest.filter(item => !only || only.includes(item.name));
const svgCache = new Map();
for (const item of selected) await verifySvgPng(dir, item, { cache: svgCache });
if (!dryRun && existsSync(envFile)) process.loadEnvFile(envFile);
const key = dryRun ? undefined : process.env.ROBLOX_API_KEY;
const creatorType = process.env.ROBLOX_CREATOR_TYPE || 'User';
const creatorId = process.env.ROBLOX_CREATOR_ID;
if (only?.some(name => !manifest.some(item => item.name === name))) throw new Error('Unknown asset in --only.');
if (!dryRun && (!key?.trim() || !/^\d+$/.test(creatorId || '') || !['User', 'Group'].includes(creatorType))) {
  console.error('Fill ROBLOX_API_KEY, ROBLOX_CREATOR_TYPE and ROBLOX_CREATOR_ID in backend/.env.roblox-upload.');
  process.exit(1);
}
const readJson = async file => existsSync(file) ? JSON.parse(await fs.readFile(file, 'utf8')) : {};
const idsPath = path.join(dir, 'asset_ids.json');
const statePath = path.join(dir, 'upload_state.json');
const ids = await readJson(idsPath);
const state = await readJson(statePath);
let writes = Promise.resolve();
const atomic = async (file, data) => {
  await fs.writeFile(`${file}.tmp`, data);
  await fs.rename(`${file}.tmp`, file);
};
function save() {
  writes = writes.then(async () => {
    await atomic(statePath, JSON.stringify(state, null, 2) + '\n');
    await atomic(idsPath, JSON.stringify(ids, null, 2) + '\n');
    const lines = ['--!strict', '', '-- GENERATED by design/upload_home_assets.mjs.',
      '-- Raw Image asset IDs; text remains editable in HomeScreen.luau.', 'local HomeAssets = {',
      ...manifest.map(item => `\t${item.name} = ${ids[item.name] || 0},`), '}', '', 'return table.freeze(HomeAssets)', ''];
    await atomic(path.join(here, '../src/Shared/HomeAssets.luau'), lines.join('\n'));
  });
  return writes;
}
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
async function request(method, endpoint, body) {
  for (let attempt = 0; attempt < 5; attempt++) {
    const response = await fetch(`${api}/${endpoint}`, { method, body, headers: { 'x-api-key': key },
      redirect: 'error', signal: AbortSignal.timeout(60000) });
    if (response.status === 429 || (method === 'GET' && response.status >= 500)) {
      await delay(Math.min(10000, 1000 * 2 ** attempt));
      continue;
    }
    if (!response.ok) {
      const detail = (await response.text()).replaceAll(key, '[redacted]').slice(0, 350);
      throw new Error(`Roblox ${method} failed (${response.status}): ${detail}`);
    }
    return response.json();
  }
  throw new Error('Roblox rate limit or temporary failure; run again to resume.');
}
function assetId(response) {
  const id = Number(response?.assetId || response?.path?.split('/').pop());
  if (!Number.isSafeInteger(id) || id <= 0) throw new Error('Roblox returned an invalid image asset ID.');
  if (response.assetType && !['Image', 'IMAGE', 'ASSET_TYPE_IMAGE'].includes(response.assetType)) {
    throw new Error(`Expected a raw Image, received ${response.assetType}. No GUI ID was applied.`);
  }
  return id;
}
async function upload(item) {
  const bytes = await fs.readFile(path.join(dir, item.file));
  if (!bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) throw new Error('Not a PNG.');
  if (bytes.length > 20 * 1024 * 1024 || bytes.readUInt32BE(16) >= 8000 || bytes.readUInt32BE(20) >= 8000) {
    throw new Error('Image exceeds Roblox upload limits.');
  }
  if (dryRun) { console.log(`ready ${item.name}: ${bytes.readUInt32BE(16)}x${bytes.readUInt32BE(20)}`); return; }
  const hash = createHash('sha256').update(bytes).digest('hex');
  const owner = `${creatorType}:${creatorId}`;
  let entry = state[item.name];
  const same = entry?.hash === hash && entry?.owner === owner;
  if (same && ids[item.name] && !args.includes('--force')) { console.log(`skip ${item.name}`); return; }
  if (!same || args.includes('--force')) entry = undefined;
  if (!entry?.operation && !entry?.assetId) {
    const form = new FormData();
    form.append('request', JSON.stringify({ assetType: 'Image', displayName: `Forge Home ${item.name}`,
      description: `Text-free ${item.name} component for Forge UGC Home.`,
      creationContext: { creator: { [creatorType === 'Group' ? 'groupId' : 'userId']: creatorId } } }));
    form.append('fileContent', new Blob([bytes], { type: 'image/png' }), `${item.name}.png`);
    const result = await request('POST', 'assets', form);
    entry = state[item.name] = { hash, owner, operation: result.path };
    if (result.done && result.error) throw new Error('Roblox rejected the upload operation.');
    if (result.done && result.response) entry.assetId = assetId(result.response);
    await save();
  }
  if (entry.operation && !/^operations\/[a-zA-Z0-9_-]+$/.test(entry.operation)) throw new Error('Invalid operation path.');
  for (let attempt = 0; attempt < 60; attempt++) {
    let response;
    if (entry.assetId) {
      response = await request('GET', `assets/${entry.assetId}?readMask=moderationResult`);
    } else {
      const operation = await request('GET', entry.operation);
      if (operation.error) {
        delete state[item.name];
        await save();
        throw new Error(`Upload rejected: ${operation.error.message || operation.error.code || 'unknown reason'}`);
      }
      if (!operation.done || !operation.response) { await delay(5000); continue; }
      response = operation.response;
      entry.assetId = assetId(response);
      await save();
    }
    const moderation = (response.moderationResult?.moderationState || '').toUpperCase();
    entry.moderation = moderation;
    if (moderation.includes('REJECTED')) {
      await save();
      throw new Error('Image rejected by Roblox moderation.');
    }
    if (moderation.includes('APPROVED')) {
      ids[item.name] = entry.assetId;
      await save();
      console.log(`ok ${item.name} -> ${entry.assetId}`);
      return;
    }
    await delay(5000);
  }
  await save();
  console.log(`pending ${item.name}: saved processing state; re-run to resume without another upload.`);
  process.exitCode = 2;
}
// Three independent assets at a time; state writes are serialized.
let cursor = 0;
await Promise.all(Array.from({ length: Math.min(3, selected.length) }, async () => {
  while (cursor < selected.length) {
    const item = selected[cursor++];
    try { await upload(item); }
    catch (error) { console.error(`FAIL ${item.name}: ${String(error.message).replaceAll(key || '\0', '[redacted]')}`); process.exitCode = 1; }
  }
}));
await writes;
if (!dryRun) console.log(`${manifest.filter(item => ids[item.name]).length}/${manifest.length} approved Images wired into HomeAssets.luau.`);
